### PR TITLE
Add `include` to multispec matrix

### PR DESCRIPTION
**Pull request by frenzymadness**
This adds a possibility to use `include` in a multispec matrix which is useful when you have a lot of possible combinations but you are interested only in a few of them. In that case, `include` is also easier to maintain when you add a new version into the multispec.

I did a little bit of refactoring because the method `check_matrix_combinations` had multiple purposes – it returned True/False for all matrix combinations and a data structure for `combination_extras`.

And now:
* Function `is_in_matrix` returns True/False if a combination of the distro and all the selectors is found in matrix. It does not care about include/exclude, that's handled on `verify_selectors` level.
* Function `get_extras` is there only for `combination_extras` returning all structures for which distro and selectors combinations fit.

Having both `include` and `exclude` in a single matrix is prohibited.

Tests are adjusted and some of them are new for the new functionality.

Fixes: #128

### CODE REVIEW

**Review by zmiklank — APPROVED** [review]
Thank you for this PR. I did not find any issue with it. LGTM.

**Comment by frenzymadness** [comment]
> Thank you for this PR. I did not find any issue with it. LGTM.

Thanks for the review! Will we wait for another one from the team?

**Comment by praiskup** [comment]
> Will we wait for another one from the team?

No need to, my 2c.  But +1 from me, too.

**Comment by zmiklank** [comment]
Great, I will also create a new release today or tomorrow.

**Pull request merged**
