### PR TITLE
Use setuptools.setup to be able to use running develop

### PR DESCRIPTION
**Pull request by bkabrda**

### CODE REVIEW

**Comment by praiskup** [comment]
Now, when I go to `rpm` directory -> make command fails for me:
```
...
rm -rf *.src.rpm *.tar.gz distgen-*
cd .. ; python setup.py sdist --owner=root --group=root --dist-dir rpm
/usr/lib/python2.7/site-packages/setuptools/dist.py:361: UserWarning: The version specified ('0.11~dev') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
  "details." % self.metadata.version
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: option --owner not recognized
make: *** [Makefile:31: "distgen-0.11~dev.tar.gz"] Error 1
```

**Comment by bkabrda** [comment]
Whoops, sorry. I added a commit that makes version conform to PEP 440, so that should fix it.

**Comment by praiskup** [comment]
Hms, `0.11.dev > 0.11` while `0.11~dev < 0.11` in RPM world...  So I used the `~` intentionally.  Well, to comply with PEP I'll have to change the versioning scheme anyways :/.

Btw. setuptools don't accept --owner and --group:
```
$ python setup.py sdist --owner=root --group=root --dist-dir rpm
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: option --owner not recognized
```
What's the way to avoid putting my username into tarball with setuptools?

**Comment by praiskup** [comment]
@bkabrda wrote:
> to be able to use running develop

What do you mean by develop?

**Comment by bkabrda** [comment]
By develop, I mean using `python setup.py develop`, it's a really convenient thing [1]. I'm honestly not sure about the `--owner` and `--group` flags, but I can certainly look into this if you give me some more time.

[1] https://stackoverflow.com/a/19048754/1937980

**Comment by bkabrda** [comment]
So I wasn't able to find any references explaining why setuptools removed these argument and from a brief investigation it seems that noone really cares about this - e.g. Django and Flask, which are among most popular PyPI packages, have usernames and groups embedded in archives. If this is an issue for you, I could possibly ask setuptools upstream to readd these, but I think noone really cares about this.

**Comment by praiskup** [comment]
The `--owner`/`--group` is not that important; I just wasn't that much proud to be noticed in the release tarball ;) but when nobody cares..

Merged, thanks!

**Comment by praiskup** [comment]
copr build https://copr.fedorainfracloud.org/coprs/build/591484/

**Pull request closed without merging**
