### PR TITLE
RFC: Multispec

### PR DESCRIPTION
**Pull request by bkabrda**
So I was trying to have a repo where I'd need a more complex "matrix" of builds, e.g. building 2 versions of software for 3 distros. The problems that I needed to solve:

* How does my CI tell what distros and versions it should build?
* Could I keep all the relevant info in one spec file instead of having multiple files like `2.2.yaml` file, that would only contain `version: 2.2`?

To that end, I implemented a concept that I call multispec. The idea is somewhat similar to that of `.travis.yml`, in the sense that it determines a build matrix and an information for all combinations inside that matrix. The implementation is definitely not final, right now I'm looking for a thumbsup/thumbsdown on this concept.

An example repo using it is at [1] (commit [2])- note especially the `multispec.yml` file [3], which defines the individual specs (a spec for two fedora distros or, spec for centos 7, spec for version 2.2 and spec for version 2.4). The idea is that distgen will know how to build any combination of the specs inside this file (this is already implemented in the PR), it will also know what all the allowed combinations are and will be able to print them (not yet implemented) and it will be able to add arbitrary more axes of the matrix without having to edit bunch of tiny yaml files.

This is currently implemented as an optional feature. It can be used by passing `--multispec <path>` and `--multispec-selector <foo>=<bar>` (e.g. `--multispec-selector version=2.2`). Multispec can also be combined with the previously implemented `--spec`, hence using that as "defaults", that get added (or possibly overwritten) by values from multispec.

Please let me know if this makes sense to you. If so, I'll clean up the implementation, add some missing bits and also create documentation and tests. Thanks!

[1] https://github.com/bkabrda/container-image-template-dg
[2] https://github.com/bkabrda/container-image-template-dg/commit/73f897874487894ae21d1a52699ccf0da20a74dd
[3] https://github.com/bkabrda/container-image-template-dg/blob/master/specs/multispec.yml

### CODE REVIEW

**Comment by praiskup** [comment]
Looks interesting.  Maybe this all is a better than maintain the matrix directly in Makefile (which was my original thought). And the code seems to fit in nicely :) - no problem to merge.

**Comment by bkabrda** [comment]
Ok, thanks. I'll work on some docs, examples and tests, add couple more commits and then ping you when I think this is ready to be merged.

**Comment by TomasTomecek** [comment]
> docs, examples, tests

@bkabrda++

**Comment by praiskup** [comment]
Looks OK.

If you plan to add a tests and you find the testsuite ugly (known issue), feel free to add separate test-suite script and hook it into `make check`.

**Comment by bkabrda** [comment]
Yeah, I'm working on tests right now. I think adding a separate unit-test suite makes sense, but I'd like to do that separately from this PR, so for now I'll just add a test that is similar to what's already present.

**Comment by bkabrda** [comment]
I added a simple test and fixed one bug, but I'd still like to add functionality to validate the multispec file and perhaps make errors not print the traceback and fail with nice message, so just like 2 more commits and this should be ready for merge :)

**Comment by bkabrda** [comment]
Ok, so I added simple validation and a try/except for various multispec failures. The validation could probably be done smarter if we wanted to include another dependency, e.g. jsonschema or similar, but I think that at least for now the validation is so easy that introducing a new dep isn't worth it. We can reconsider in the future if we find that we need to add and maintain validation of several different versions of the multispec.

Hence, I think this is ready for final review and merge.

**Comment by praiskup** [comment]
Feel free to merge.

**Comment by bkabrda** [comment]
Thanks! Merging...

**Pull request merged**
