### PR TITLE
Fix 'python setup.py install --user'

### PR DESCRIPTION
**Pull request by praiskup**
.. and virtualenv's 'python setup.py install'.

I'm not really convinced this is 100% correct way of thinking, so please take this as concept I'd like to discuss :)

### CODE REVIEW

**Comment by praiskup** [comment]
OK, experiment failed for python3.6 and I'm not sure why, but does it even make sense to continue with this?

**Comment by praiskup** [comment]
Hm, 3.6 started to work now.  Please ignore the "push" CI run, I mistakenly pushed to new branch here, and I immediately removed that branch.

**Comment by bkabrda** [comment]
Reopening as per https://github.com/devexp-db/distgen/pull/82#issuecomment-382401603

**Comment by praiskup** [comment]
Seems like 'python setup.py install --user' still isn't working anyways.

**Comment by praiskup** [comment]
Sorry, it seems to work for me now.  I probably did some mistake before.

**Comment by praiskup** [comment]
staled

**Pull request closed without merging**
