### PR TITLE
Add .travis.yml section to do auto deploys of tagged commits

### PR DESCRIPTION
**Pull request by bkabrda**

### CODE REVIEW

**Comment by praiskup** [comment]
Hms, could random observer submit PR with hack revealing your deploy->password->secure value?

**Comment by bkabrda** [comment]
@praiskup the secure value is visible by default, but noone will be able to decrypt it except travis. Is there a specific attack scenario that you have in mind?

**Comment by praiskup** [comment]
Ah, I was told this is executed only after-merge;  which needs to be done by approved committer.  Feel free to merge.

**Comment by bkabrda** [comment]
Thanks, merging.

**Pull request merged**
