### PR TITLE
Use importlib instead of deprecated imp

### PR DESCRIPTION
**Pull request by frenzymadness**
Also, imp has been removed in Python 3.12

### CODE REVIEW

**Comment by frenzymadness** [comment]
It seems that we're gonna need some if/else for epel 7.

**Comment by frenzymadness** [comment]
So, the functionality is fixed and works in rawhide as well as epel7. Now, the question is how to make the linter happy.

**Comment by zmiklank** [comment]
What about silencing the `used-before-assignment` warning for this specific block of code? Using of the `imp` module seems correct to me, from my pov this is mistake of the pylint.

**Comment by frenzymadness** [comment]
Technically speaking, it's possible to call `_load_python_file_imp` without `imp` being available but it's private method and I honestly like this solution more than having a big if/else block in the function or on the class level defining the function one way or another. But this is just my preference and I've hopefully silenced the linter so feel free to voice what you think.

**Review by zmiklank — APPROVED** [review]
LGTM, @praiskup do you have any notes for this PR?

**Comment by praiskup** [comment]
No, just **thank you** for the work here!

**Comment by zmiklank** [comment]
Yes. Thank you Lumir :). I am going to merge this then.

**Pull request merged**
