### PR TITLE
use fedora base image from Fedora registry

### PR DESCRIPTION
**Pull request by TomasTomecek**
this is Fedora policy for container review process

Signed-off-by: Tomas Tomecek <ttomecek@redhat.com>

### CODE REVIEW

**Comment by bkabrda** [comment]
This LGTM, but you'll have to fix the `tests/minimal-dockerfile/test.out` to change the registry name there, otherwise the tests won't pass.

**Comment by TomasTomecek** [comment]
sorry about it, forgot you guys have impressive tests; they are passing for me right now:

```
testing: /home/tt/g/distgen/tests/dockerfile
testing: /home/tt/g/distgen/tests/docker-cmd
testing: /home/tt/g/distgen/tests/docker-entrypoint
testing: /home/tt/g/distgen/tests/docker-labels
testing: /home/tt/g/distgen/tests/macros
testing: /home/tt/g/distgen/tests/macros-cmdline
testing: /home/tt/g/distgen/tests/macros-from
testing: /home/tt/g/distgen/tests/macros-short
testing: /home/tt/g/distgen/tests/minimal-dockerfile
testing: /home/tt/g/distgen/tests/multispec
testing: /home/tt/g/distgen/tests/pkginstaller
testing: /home/tt/g/distgen/tests/no-spec
testing: 'dg --output out' matches 'dg > out'
success
```

**Comment by bkabrda** [comment]
CI is green and LGTM => merging. Thanks!

**Comment by TomasTomecek** [comment]
you need to click the button :D

**Comment by bkabrda** [comment]
@TomasTomecek I'm tired :D

**Pull request merged**
